/**
 * Build-time image pipeline.
 *
 * Reads src/assets/*.{jpg,png} and emits AVIF + WebP + an original-format
 * fallback at each width into public/img/, plus a typed manifest at
 * src/generated/images.ts.
 *
 * Deliberately not a Vite plugin: the project pins Vite 8 behind a vendored
 * config preset, and a bundler plugin is the fragile part of that stack. Plain
 * files under public/ are served verbatim by every host and every dev server.
 *
 * Incremental — an output newer than its source is left alone. Run with
 * --force to regenerate everything.
 */
import sharp from "sharp";
import { readdirSync, statSync, mkdirSync, writeFileSync, existsSync, rmSync } from "node:fs";
import { join, parse, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "src", "assets");
const OUT = join(ROOT, "public", "img");
const MANIFEST = join(ROOT, "src", "generated", "images.ts");

const WIDTHS = [480, 768, 1024, 1440, 1920];
const FORCE = process.argv.includes("--force");

/** Photographs are rendered monochrome, so chroma can be cheap. */
const Q = { avif: 50, webp: 72, jpeg: 78 };

mkdirSync(OUT, { recursive: true });
mkdirSync(dirname(MANIFEST), { recursive: true });

const sources = readdirSync(SRC).filter((f) => /\.(jpe?g|png)$/i.test(f));
const manifest = {};
let wrote = 0;
let skipped = 0;

for (const file of sources) {
  const abs = join(SRC, file);
  const { name, ext } = parse(file);
  const key = name;
  const srcStat = statSync(abs);

  const image = sharp(abs);
  const meta = await image.metadata();
  const hasAlpha = Boolean(meta.hasAlpha);

  /* Photos fall back to JPEG, which is cheap. Transparent images do NOT get a
   * PNG fallback: the mascot's PNG is 324 KB against 55 KB for AVIF, and the
   * only browsers lacking WebP also lack svh, color-mix and the rest of what
   * this site is built on. WebP is the floor. */
  const fallbackExt = hasAlpha ? "webp" : "jpg";
  const formats = hasAlpha ? ["avif", "webp"] : ["avif", "webp", "jpg"];

  // never upscale past the source
  const widths = WIDTHS.filter((w) => w <= meta.width);
  if (widths.length === 0) widths.push(meta.width);

  /* The fallback is served to one browser generation at one size; there is no
   * point emitting it at every width only to prune it again next run. */
  const fbWidth = widths.includes(1024) ? 1024 : widths[widths.length - 1];

  const entry = {
    width: meta.width,
    height: meta.height,
    aspect: +(meta.width / meta.height).toFixed(4),
    alpha: hasAlpha,
    avif: [],
    webp: [],
    fallback: "",
  };

  for (const w of widths) {
    for (const fmt of formats) {
      if (fmt === "jpg" && w !== fbWidth) continue;
      const outName = `${name}-${w}.${fmt}`;
      const outPath = join(OUT, outName);
      const fresh = !FORCE && existsSync(outPath) && statSync(outPath).mtimeMs >= srcStat.mtimeMs;

      if (!fresh) {
        const pipe = sharp(abs).resize({ width: w, withoutEnlargement: true });
        if (fmt === "avif") await pipe.avif({ quality: Q.avif, effort: 6 }).toFile(outPath);
        else if (fmt === "webp") await pipe.webp({ quality: Q.webp, effort: 5 }).toFile(outPath);
        else if (fmt === "png")
          await pipe.png({ compressionLevel: 9, palette: true, quality: 82 }).toFile(outPath);
        else await pipe.jpeg({ quality: Q.jpeg, mozjpeg: true }).toFile(outPath);
        wrote++;
      } else {
        skipped++;
      }

      const url = `/img/${outName}`;
      const size = statSync(outPath).size;
      if (fmt === "avif") entry.avif.push({ w, url, size });
      else if (fmt === "webp") entry.webp.push({ w, url, size });
    }
  }

  entry.fallback = `/img/${name}-${fbWidth}.${fallbackExt}`;
  manifest[key] = entry;

  const largestAvif = Math.max(...entry.avif.map((v) => v.size));
  console.log(
    `${key.padEnd(20)} ${String(meta.width).padStart(5)}x${String(meta.height).padEnd(5)} ` +
      `${hasAlpha ? "alpha" : "     "}  avif max ${(largestAvif / 1024).toFixed(1)} KB  (was ${(srcStat.size / 1024).toFixed(1)} KB)`,
  );
}

// prune outputs whose source no longer exists
const valid = new Set();
for (const [k, e] of Object.entries(manifest)) {
  for (const v of [...e.avif, ...e.webp]) valid.add(v.url.replace("/img/", ""));
  valid.add(e.fallback.replace("/img/", ""));
}
for (const f of readdirSync(OUT)) {
  if (!valid.has(f)) {
    rmSync(join(OUT, f));
    console.log("pruned " + f);
  }
}

const banner = `/* GENERATED by scripts/images.mjs — do not edit. Run \`bun run images\`. */\n`;
const types = `
export type ImageVariant = { w: number; url: string; size: number };
export type ImageEntry = {
  width: number;
  height: number;
  aspect: number;
  alpha: boolean;
  avif: ImageVariant[];
  webp: ImageVariant[];
  fallback: string;
};
export type ImageKey = keyof typeof images;
`;
writeFileSync(
  MANIFEST,
  `${banner}${types}\nexport const images = ${JSON.stringify(manifest, null, 2)} as const satisfies Record<string, ImageEntry>;\n`,
  "utf8",
);

const total = Object.values(manifest).reduce(
  (a, e) => a + Math.max(...e.avif.map((v) => v.size)),
  0,
);
console.log(
  `\n${sources.length} sources — wrote ${wrote}, skipped ${skipped}. ` +
    `Sum of largest AVIF per image: ${(total / 1024).toFixed(0)} KB`,
);
