import type { ImageKey } from "@/generated/images";

/**
 * The roster entries that currently have a preview. A release without a clip
 * simply does not appear here — the player never offers a track it cannot
 * actually play.
 */
export type Track = {
  id: string;
  title: string;
  artist: string;
  year: string;
  genre: string;
  cover: ImageKey;
  /** REPLACE — placeholder clips generated by scripts/audio.mjs */
  src: string;
};

export const tracks: Track[] = [
  {
    id: "rusted-gold",
    title: "Rusted Gold",
    artist: "Rana & The Strays",
    year: "2025",
    genre: "Post-punk",
    cover: "release-01",
    src: "/audio/rusted-gold.wav",
  },
  {
    id: "terminus",
    title: "Terminus",
    artist: "Tram No. 12",
    year: "2024",
    genre: "Instrumental",
    cover: "release-04",
    src: "/audio/terminus.wav",
  },
  {
    id: "park-circus",
    title: "Park Circus Edits",
    artist: "DJ Shona",
    year: "2023",
    genre: "Club",
    cover: "release-06",
    src: "/audio/park-circus.wav",
  },
];

export const trackForArtist = (artist: string) => tracks.find((t) => t.artist === artist);
